/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        background: "#0d1117",
        foreground: "#e6edf3",
        surface: "#161b22",
        "surface-border": "#30363d",
        "surface-hover": "#21262d",
        card: "#161b22",
        "card-foreground": "#e6edf3",
        popover: "#161b22",
        "popover-foreground": "#e6edf3",
        primary: "#58a6ff",
        "primary-light": "#79c0ff",
        "primary-foreground": "#ffffff",
        secondary: "#21262d",
        "secondary-foreground": "#c9d1d9",
        muted: "#21262d",
        "muted-foreground": "#8b949e",
        accent: "#21262d",
        "accent-foreground": "#f0f6fc",
        destructive: "#f85149",
        "destructive-foreground": "#ffffff",
        border: "#30363d",
        input: "#30363d",
        ring: "#58a6ff",
        success: "#2ea043",
        warning: "#d29922",
        danger: "#f85149",
        baseline: "#f85149",
        icm: "#2ea043",
      },
    },
  },
  plugins: [],
};
